# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["gh-workflows"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages:    write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: .ci_support/environment.yaml
      - name: Configure Project
        run: |
          mkdir conf
          echo -n "$GITHUB_WORKSPACE/deps/emscripten-forge" > conf/emscripten-forge-dir
          echo -n "$GITHUB_WORKSPACE/deps/swift" > conf/swift-dir
          echo -n "$GITHUB_WORKSPACE/deps/react-swift" > conf/react-swift-dir
          echo -n "$GITHUB_WORKSPACE/deps/emsdk" > conf/emsdk-dir
          echo -n "$GITHUB_WORKSPACE/deps/pyjs-code-runner" > conf/pyjs-code-runner-dir
          $SHELL ./scripts/setup.sh
        shell: bash
      - name: Build Swift
        run: |
          $SHELL ./scripts/build.sh
        shell: bash
